//
//  Hdc.swift
//  Crochet
//
//  Created by BR on 13.06.2023.
//  Copyright © 2023 CompanyName. All rights reserved.
//
//  Generated by PaintCode
//  http://www.paintcodeapp.com
//
//  This code was generated by Trial version of PaintCode, therefore cannot be used for commercial purposes.
//



import UIKit

public class Hdc : NSObject {

    //// Drawing Methods

//    @objc dynamic public class func drawElement(frame targetFrame: CGRect = CGRect(x: 0, y: 0, width: 179, height: 100), resizing: ResizingBehavior = .aspectFit, fillColor: UIColor = UIColor(red: 0.000, green: 0.000, blue: 0.000, alpha: 1.000)) {
//        //// General Declarations
//        let context = UIGraphicsGetCurrentContext()!
//        
//        //// Resize to Target Frame
//        context.saveGState()
//        let resizedFrame: CGRect = resizing.apply(rect: CGRect(x: 0, y: 0, width: 179, height: 100), target: targetFrame)
//        context.translateBy(x: resizedFrame.minX, y: resizedFrame.minY)
//        context.scaleBy(x: resizedFrame.width / 179, y: resizedFrame.height / 100)
//
//
//        //// Oval Drawing
//        let ovalPath = UIBezierPath(ovalIn: CGRect(x: 4.5, y: 1.5, width: 170, height: 96))
//        fillColor.setFill()
//        ovalPath.fill()
//        fillColor.setStroke()
//        ovalPath.lineWidth = 3
//        ovalPath.stroke()
//        
//        context.restoreGState()
//
//    }

    @objc dynamic public class func drawElement(frame targetFrame: CGRect = CGRect(x: 0, y: 0, width: 107, height: 138), resizing: ResizingBehavior = .aspectFit, fillColor: UIColor = UIColor(red: 0.000, green: 0.000, blue: 0.000, alpha: 1.000)) {
        //// General Declarations
        let context = UIGraphicsGetCurrentContext()!
        
        //// Resize to Target Frame
        context.saveGState()
        let resizedFrame: CGRect = resizing.apply(rect: CGRect(x: 0, y: 0, width: 107, height: 138), target: targetFrame)
        context.translateBy(x: resizedFrame.minX, y: resizedFrame.minY)
        context.scaleBy(x: resizedFrame.width / 107, y: resizedFrame.height / 138)


        //// Bezier 2 Drawing
        let bezier2Path = UIBezierPath()
        bezier2Path.move(to: CGPoint(x: -0.5, y: 0.5))
        bezier2Path.addLine(to: CGPoint(x: 107.5, y: 0.5))
        fillColor.setFill()
        bezier2Path.fill()
        fillColor.setStroke()
        bezier2Path.lineWidth = 3
        bezier2Path.stroke()


        //// Bezier Drawing
        let bezierPath = UIBezierPath()
        bezierPath.move(to: CGPoint(x: 53.5, y: 0.5))
        bezierPath.addLine(to: CGPoint(x: 53.5, y: 138.5))
        fillColor.setFill()
        bezierPath.fill()
        fillColor.setStroke()
        bezierPath.lineWidth = 3
        bezierPath.stroke()
        
        context.restoreGState()

    }




    @objc(HdcResizingBehavior)
    public enum ResizingBehavior: Int {
        case aspectFit /// The content is proportionally resized to fit into the target rectangle.
        case aspectFill /// The content is proportionally resized to completely fill the target rectangle.
        case stretch /// The content is stretched to match the entire target rectangle.
        case center /// The content is centered in the target rectangle, but it is NOT resized.

        public func apply(rect: CGRect, target: CGRect) -> CGRect {
            if rect == target || target == CGRect.zero {
                return rect
            }

            var scales = CGSize.zero
            scales.width = abs(target.width / rect.width)
            scales.height = abs(target.height / rect.height)

            switch self {
                case .aspectFit:
                    scales.width = min(scales.width, scales.height)
                    scales.height = scales.width
                case .aspectFill:
                    scales.width = max(scales.width, scales.height)
                    scales.height = scales.width
                case .stretch:
                    break
                case .center:
                    scales.width = 1
                    scales.height = 1
            }

            var result = rect.standardized
            result.size.width *= scales.width
            result.size.height *= scales.height
            result.origin.x = target.minX + (target.width - result.width) / 2
            result.origin.y = target.minY + (target.height - result.height) / 2
            return result
        }
    }
}
